/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Depoimento = {
  _id: string;
  _type: "depoimento";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeCliente?: string;
  cargoEmpresa?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  texto?: string;
  nota?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Galeria = {
  _id: string;
  _type: "galeria";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  imagens?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type CategoriaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "categoria";
};

export type Video = {
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  url?: string;
  categoria?: CategoriaReference;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type MembroEquipe = {
  _id: string;
  _type: "membroEquipe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cargo?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  redesSociais?: Array<{
    rede?: "linkedin" | "instagram";
    url?: string;
    _key: string;
  }>;
  ordem?: number;
};

export type Obra = {
  _id: string;
  _type: "obra";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: CategoriaReference;
  status?: "em_andamento" | "concluida";
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitulo?: string;
  metaDescricao?: string;
  imagemOg?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Projeto = {
  _id: string;
  _type: "projeto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria?: CategoriaReference;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
};

export type Categoria = {
  _id: string;
  _type: "categoria";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  slug?: Slug;
};

export type Servico = {
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
};

export type PoliticaPrivacidade = {
  _id: string;
  _type: "politicaPrivacidade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  conteudo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
};

export type PaginaSobre = {
  _id: string;
  _type: "paginaSobre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  textoIntroducao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagemDestaque?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  missao?: string;
  visao?: string;
  valores?: Array<string>;
  mostrarEquipe?: boolean;
  seo?: Seo;
};

export type PaginaInicial = {
  _id: string;
  _type: "paginaInicial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tituloHero?: string;
  subtituloHero?: string;
  imagemFundo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  textoCta?: string;
  linkCta?: string;
  tituloCtaFinal?: string;
  subtituloCtaFinal?: string;
  textoBotaoCtaFinal?: string;
  linkBotaoCtaFinal?: string;
};

export type ConfiguracaoSite = {
  _id: string;
  _type: "configuracaoSite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeEmpresa?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  telefone?: string;
  whatsapp?: string;
  email?: string;
  endereco?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Depoimento
  | SanityImageCrop
  | SanityImageHotspot
  | Galeria
  | CategoriaReference
  | Video
  | MembroEquipe
  | Obra
  | Seo
  | Slug
  | Projeto
  | Categoria
  | Servico
  | PoliticaPrivacidade
  | PaginaSobre
  | PaginaInicial
  | ConfiguracaoSite
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: configuracaoSiteQuery
// Query: *[_type == "configuracaoSite"][0]
export type ConfiguracaoSiteQueryResult = {
  _id: string;
  _type: "configuracaoSite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeEmpresa?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  telefone?: string;
  whatsapp?: string;
  email?: string;
  endereco?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: paginaInicialQuery
// Query: *[_type == "paginaInicial"][0]
export type PaginaInicialQueryResult = {
  _id: string;
  _type: "paginaInicial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tituloHero?: string;
  subtituloHero?: string;
  imagemFundo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  textoCta?: string;
  linkCta?: string;
  tituloCtaFinal?: string;
  subtituloCtaFinal?: string;
  textoBotaoCtaFinal?: string;
  linkBotaoCtaFinal?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicosQuery
// Query: *[_type == "servico"] | order(ordem asc)
export type ServicosQueryResult = Array<{
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetosDestaqueQuery
// Query: *[_type == "projeto"] | order(_createdAt desc)[0...6]{    _id,    titulo,    slug,    capa,    categoria->{nome}  }
export type ProjetosDestaqueQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: paginaSobreQuery
// Query: *[_type == "paginaSobre"][0]
export type PaginaSobreQueryResult = {
  _id: string;
  _type: "paginaSobre";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  textoIntroducao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  imagemDestaque?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  missao?: string;
  visao?: string;
  valores?: Array<string>;
  mostrarEquipe?: boolean;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: membrosEquipeQuery
// Query: *[_type == "membroEquipe"] | order(ordem asc)
export type MembrosEquipeQueryResult = Array<{
  _id: string;
  _type: "membroEquipe";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nome?: string;
  cargo?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  redesSociais?: Array<{
    rede?: "instagram" | "linkedin";
    url?: string;
    _key: string;
  }>;
  ordem?: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: servicoBySlugQuery
// Query: *[_type == "servico" && slug.current == $slug][0]
export type ServicoBySlugQueryResult = {
  _id: string;
  _type: "servico";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  icone?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  descricaoCurta?: string;
  descricaoLonga?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  ordem?: number;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: servicoSlugsQuery
// Query: *[_type == "servico"]{ "slug": slug.current }
export type ServicoSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetosQuery
// Query: *[_type == "projeto"] | order(_createdAt desc){    _id, titulo, slug, capa, categoria->{nome}  }
export type ProjetosQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: projetoBySlugQuery
// Query: *[_type == "projeto" && slug.current == $slug][0]{    ...,    categoria->{nome}  }
export type ProjetoBySlugQueryResult = {
  _id: string;
  _type: "projeto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria: {
    nome: string | null;
  } | null;
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: projetoSlugsQuery
// Query: *[_type == "projeto"]{ "slug": slug.current }
export type ProjetoSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: obrasQuery
// Query: *[_type == "obra"] | order(_createdAt desc){    _id, titulo, slug, capa, status, categoria->{nome}  }
export type ObrasQueryResult = Array<{
  _id: string;
  titulo: string | null;
  slug: Slug | null;
  capa: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  status: "concluida" | "em_andamento" | null;
  categoria: {
    nome: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: obraBySlugQuery
// Query: *[_type == "obra" && slug.current == $slug][0]{    ...,    categoria->{nome}  }
export type ObraBySlugQueryResult = {
  _id: string;
  _type: "obra";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  slug?: Slug;
  categoria: {
    nome: string | null;
  } | null;
  status?: "concluida" | "em_andamento";
  capa?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galeria?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  descricao?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  cliente?: string;
  area?: number;
  ano?: number;
  localizacao?: string;
  seo?: Seo;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: obraSlugsQuery
// Query: *[_type == "obra"]{ "slug": slug.current }
export type ObraSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: videosQuery
// Query: *[_type == "video"] | order(_createdAt desc)
export type VideosQueryResult = Array<{
  _id: string;
  _type: "video";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  url?: string;
  categoria?: CategoriaReference;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: src/sanity/lib/queries.ts
// Variable: depoimentosQuery
// Query: *[_type == "depoimento"] | order(_createdAt desc)
export type DepoimentosQueryResult = Array<{
  _id: string;
  _type: "depoimento";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nomeCliente?: string;
  cargoEmpresa?: string;
  foto?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  texto?: string;
  nota?: number;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: politicaPrivacidadeQuery
// Query: *[_type == "politicaPrivacidade"][0]
export type PoliticaPrivacidadeQueryResult = {
  _id: string;
  _type: "politicaPrivacidade";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titulo?: string;
  conteudo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: Seo;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "configuracaoSite"][0]': ConfiguracaoSiteQueryResult;
    '*[_type == "paginaInicial"][0]': PaginaInicialQueryResult;
    '*[_type == "servico"] | order(ordem asc)': ServicosQueryResult;
    '*[_type == "projeto"] | order(_createdAt desc)[0...6]{\n    _id,\n    titulo,\n    slug,\n    capa,\n    categoria->{nome}\n  }': ProjetosDestaqueQueryResult;
    '*[_type == "paginaSobre"][0]': PaginaSobreQueryResult;
    '*[_type == "membroEquipe"] | order(ordem asc)': MembrosEquipeQueryResult;
    '*[_type == "servico" && slug.current == $slug][0]': ServicoBySlugQueryResult;
    '*[_type == "servico"]{ "slug": slug.current }': ServicoSlugsQueryResult;
    '*[_type == "projeto"] | order(_createdAt desc){\n    _id, titulo, slug, capa, categoria->{nome}\n  }': ProjetosQueryResult;
    '*[_type == "projeto" && slug.current == $slug][0]{\n    ...,\n    categoria->{nome}\n  }': ProjetoBySlugQueryResult;
    '*[_type == "projeto"]{ "slug": slug.current }': ProjetoSlugsQueryResult;
    '*[_type == "obra"] | order(_createdAt desc){\n    _id, titulo, slug, capa, status, categoria->{nome}\n  }': ObrasQueryResult;
    '*[_type == "obra" && slug.current == $slug][0]{\n    ...,\n    categoria->{nome}\n  }': ObraBySlugQueryResult;
    '*[_type == "obra"]{ "slug": slug.current }': ObraSlugsQueryResult;
    '*[_type == "video"] | order(_createdAt desc)': VideosQueryResult;
    '*[_type == "depoimento"] | order(_createdAt desc)': DepoimentosQueryResult;
    '*[_type == "politicaPrivacidade"][0]': PoliticaPrivacidadeQueryResult;
  }
}
